### ISSUE TITLE
Deserialization on int maps to System.Int64 in 5.x and System.Int32 in 4.x

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#128] opened 2015-04-18 17:11 UTC
We should understand the reason for the changes.

**Comment by brentschmaltz** [comment] 2015-05-27 23:59
in 4.x we use JavaScriptSerializer, in 5.x we use NewtonSoft which performs a different mapping.

**Comment by tushargupta51** [comment] 2015-08-13 23:43
It is by design that JsonConvert deserialize int to Int64. Here is a related workitem:http://json.codeplex.com/workitem/20832

The issue was closed with this description:
"Json.NET by default reads integer values as Int64 because there is no way to know whether the value should be Int32 or Int64, and Int64 is less likely to overflow. For a typed property the deserializer knows to convert the Int64 to a Int32 but because your property is untyped you are getting an Int64. 
That bit of source code you posted isn't a bug, I did that so that the BsonReader and JsonTextReader produce consistent results. It is just the way Json.NET has to work. "

There is a StackOverflow question (http://stackoverflow.com/questions/8297541/how-do-i-change-the-default-type-for-numeric-deserialization/9444519#9444519) that talks about the same issue. It seems that the only way to make JsonConvert return Int32 is to override it, which does not seem like something we should do.

I will add an update on this in the changelog and close the issue.

**Closed** 2015-08-18 21:36 UTC
Labels: Fix 5.x, P2
