### ISSUE TITLE
Alg still wrong?

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#400] opened 2016-05-18 16:18 UTC
I still get the weird XML identifier for alg in a JWT in RC2. Wasn't that fixed?

**Comment by brentschmaltz** [comment] 2016-05-19 18:10
@leastprivilege we removed the outbound mapping.
What are you seeing?

**Comment by brockallen** [comment] 2016-05-19 23:08
JWTs have this for the header:

```
{
  "alg": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
  "kid": "6B7ACC520305BFDB4F7252DAEB2177CC091FAAE1",
  "typ": "JWT"
}
```

The `alg` is wrong.

**Comment by brentschmaltz** [comment] 2016-05-23 17:23
@leastprivilege , @brockallen it looks so you are looking for the outbound mapping (where we had an equivalence class of algorithms that were mapped to the JWT ns) to be re-installed. 
Our thought was, the user set the algorithm on SigningCredentials and we didn't want to mess with it.
But, we are hearing that it was somewhat useful.

**Comment by brockallen** [comment] 2016-05-24 10:50
I don't follow. The JWA spec does not list that `alg`:

https://tools.ietf.org/html/rfc7518#section-3.1

**Comment by PinpointTownes** [comment] 2016-05-24 15:36
@leastprivilege @brockallen not sure it's worth arguing. I've tried hard and lamentably failed: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/317#issuecomment-163076860.

**Comment by brockallen** [comment] 2016-05-24 15:50
Right, but JWTs/id_tokens produced by this library will then fail to validate.

**Comment by brentschmaltz** [comment] 2016-05-24 18:40
@brockallen @PinpointTownes that is a good point that we will fail to inter-operate.
We will try and fit this in, outbound mapping only.

**Comment by leastprivilege** [comment] 2016-05-24 19:07
Thank god @brockallen discovered this issue. Was a tricky one.

**Comment by PinpointTownes** [comment] 2016-05-24 19:20
@leastprivilege actually, it's not really new: two ASOS users reported this issue in November and I immediately informed the Azure AD team about the implications of this change:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/300#discussion_r45013780
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/316

![image](https://cloud.githubusercontent.com/assets/6998306/15516766/a4e110de-21f4-11e6-9ada-9ac68d89bbba.png)

Almost 7 months later, it's still not fixed... but I guess it's probably better to waste time working on the XML documentation or polishing the exception messages rather than fixing this kind of bugs. After all, who cares if the JWT issued by IdentityModel don't use standard-compliant JWA algorithms...

**Comment by brentschmaltz** [comment] 2016-05-24 22:38
@PinpointTownes now now, we weren't convinced it was needed. It is up to the user to set the outbound algorithm. But now we agree that it will help.

Exception messages are important to get right.

**Comment by brentschmaltz** [comment] 2016-05-24 22:41
@PinpointTownes @brockallen If there are any other nagging items, please speak up so we have a chance to get them in.

**Comment by leastprivilege** [comment] 2016-05-25 05:13
@PinpointTownes that was sarcasm - but never mind ;)

**Comment by PinpointTownes** [comment] 2016-05-25 17:23
@leastprivilege my sarcasm radar must be broken, then :smile: 

@brentschmaltz so, is this something you'll fix for RTM?

**Comment by brockallen** [comment] 2016-05-25 18:46
> @brentschmaltz so, is this something you'll fix for RTM?

If not, then I doubt we can use this library in IdentityServer. Maybe that's by design? :)

**Comment by PinpointTownes** [comment] 2016-05-25 18:58
FWIW, my PR was ready to be merged: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/317/files. Would you like me to rebase it?

My approach was clear:
  - Remove the totally insane mix between XMLDsig and JWA identifiers in `SecurityAlgorithms` and opt for one standard only. For consistency with IdentityModel 4, I opted for the XMLDsig identifiers.
  - Make the appropriate mapping directly in `JwtSecurityTokenHandler` to avoid returning XMLDsig identifiers (ideally, we should also prevent JWT tokens using a XMLDsig `alg` header from being validated, but you were opposed to that...).

**Comment by brentschmaltz** [comment] 2016-05-25 20:48
@PinpointTownes @brockallen We are going to fix at least outbound for RTM.

**Comment by PinpointTownes** [comment] 2016-05-25 21:06
> The spec is open for alg's.

It is, but I don't think that's a reason to accept XML security algorithms (at least by default).

And hem, it's really urgent to fix your stuff. There are currently many methods where things are totally mixed up (digest/hash algorithms instead of signature algorithms...).

Even your unit tests are impacted by this mess: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/test/Microsoft.IdentityModel.Protocols.OpenIdConnect.Tests/OpenIdConnectProtocolValidatorTests.cs#L276.

**Comment by brentschmaltz** [comment] 2016-05-25 21:28
To that point, our extensibility in OpenIdConnectProtocolValidator is lacking.

**Comment by PinpointTownes** [comment] 2016-05-25 21:45
> To that point, our extensibility in OpenIdConnectProtocolValidator is lacking.

It's so much more than an extensibility issue, actually.

**Comment by brentschmaltz** [comment] 2016-05-25 22:02
I was referring to below, where the user may have difficulties creating a custom algorithm as the algorithms are fixed, of course the method is virtual, but not tied to the HashAlgorithmMap.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs#L439

I think you are referring to this (also Sha384, Sha512), which is obviously an error.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs#L432

**Comment by PinpointTownes** [comment] 2016-05-25 22:08
> which is obviously an error.

An error I reported 7 months ago: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/317/files#r45627961 :smile:

**Comment by brentschmaltz** [comment] 2016-05-25 22:10
Is it too late to say Thank-You :blush:

**Comment by PinpointTownes** [comment] 2016-05-25 22:12
I'm not here for glory ; fix it, and you'll make me happy :smile:

**Comment by m-andrew-albright** [comment] 2016-06-02 18:45
I would like this to be fixed as well.  This completely derails our ability to validate signed JWTs from our Identity Server.

**Comment by brentschmaltz** [comment] 2016-06-14 16:53
@leastprivilege @PinpointTownes @m-andrew-albright https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/447

**Closed by brentschmaltz** 2016-06-14 16:53 UTC
Labels: Fix 5.x, P1, PR Submitted, Question, User reported

**Comment by PinpointTownes** [comment] 2016-06-15 22:17
Fix confirmed, thanks :clap:
