### ISSUE TITLE
Dotnet Core 2.1 broke WriteToken() on Linux kernels (ObjectDisposedException)

### ISSUE THREAD

**Issue by AaronFixer** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#944] opened 2018-06-10 02:33 UTC
System.IdentityModel.Tokens.Jwt isn't working anymore on our Linux environment when we try to generate a Jwt. 

This problem is specifically in .NET Core 2.1 when calling ` new JwtSecurityTokenHandler().WriteToken(jwt)`

An example of the bug can be found in this repo:  https://github.com/AaronFixer/RsaMicrosoftIdentityJwtLinuxBug

Just run `dotnet run` from within a Linux distro (I did this on Ubuntu 16.04 and 17.10).

**Comment by brentschmaltz** [comment] 2018-06-13 17:29
@AaronFixer I would expect that to throw because you are using the RSA object after disposing.

**Comment by AaronFixer** [comment] 2018-06-14 01:03
@brentschmaltz Where? We're not disposing the object being used: 

https://github.com/AaronFixer/RsaMicrosoftIdentityJwtLinuxBug/blob/master/Program.cs#L26

This stores the signing credentials outside of the context being disposed. 

What other object are we using after disposing? 

Again, it's important to mention, this works in Windows. It does not work in Linux. This is an OS specific problem.

**Comment by AaronFixer** [comment] 2018-06-14 09:03
Just tried changing it to all be in the same context, and actually @brentschmaltz you're correct it works.

But this still seems like a bug. Why is the object not persistent if assigned before the context is disposed? 

This doesn't make sense to me.

**Comment by vbenedichuk** [comment] 2018-06-14 11:38
@brentschmaltz thank you. Coould you please clarify why is this issue specific for .net core 2.1 on linux and not reproducible on windows? It is also not happening on .net core 2.0 neither on win nor on lin.
Does it mean that we may face with resources leak on that platforms?

**Comment by brentschmaltz** [comment] 2018-06-14 15:08
@AaronFixer @vbenedichuk the 'using' statement calls dispose on exiting the clause.
The using clause is similar to:
```
Foo foo;
using (foo = new Foo())
{ 
    foo.DoWork(); // <-- works fine
}
foo.DoWork(); //<-- throws disposed

// similar to
var foo = new foo();
foo.Dispose();
foo.DoWork(); // <--- throws disposed
```
I wouldn't jump to concluding a leak issue right away, we would have to investigate by monitoring memory.
There may be additional memory pressure, but the GC will clean up memory, not in a deterministic manner as when calling Dispose().

**Comment by brentschmaltz** [comment] 2018-06-14 21:59
@AaronFixer @vbenedichuk I am going to close this out.
Please feel free to reopen, ask other clarifying questions, we sometimes get things wrong :-)

**Closed by brentschmaltz** 2018-06-14 21:59 UTC
Labels: Investigate, User reported

**Comment by AaronFixer** [comment] 2018-06-14 22:07
@brentschmaltz This is still an issue. Because this still works on Windows OS. Meaning the actual problem seems to be the opposite. 

Why is a disposed object still available and working on the Windows OS? 

You can run this BugSample on Windows and you'll see it still works.

**Comment by brentschmaltz** [comment] 2018-06-14 23:03
@AaronFixer can you explain to me what you mean about 'still works on Windows OS'?

**Comment by AaronFixer** [comment] 2018-06-15 00:54
@brentschmaltz As you quite rightly pointed out, this issue isn't actually a bug as disposed objects shouldn't be available outside of their context. 

On Windows however,  the disposed object appears to still be available as the token is generated fine (run the code I originally submitted on Windows, and you'll see the token is generated). 

This isn't correct behavior though. As it should throw the same error (`ObjectDisposedException`).
