### ISSUE TITLE
Add net472 as a desktop target

### ISSUE THREAD

**Issue by mafurman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1329] opened 2020-02-07 22:56 UTC
Adding net472 would allow us to have a clean crypto target for desktop users, as it would contain support for ECDsa keys.

**Comment by GeoK** [comment] 2020-10-07 18:03
Closing. Duplicate of #1507

**Closed by GeoK** 2020-10-07 18:03 UTC
Labels: Internal
