### ISSUE TITLE
[Question] Implementation of Base64UrlEncoder.Decode

### ISSUE THREAD

**Issue by 8ggmaker** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1707] opened 2021-09-27 08:36 UTC
Hi Team,
I am trying to make changes to improve the Decode method of Base64UrlEncoder, and in my local test, there are some test failures, after add more logs, I find it is because the test use Base64UrlEncoder.Decode to decode a base64 string:
_rCz8Sn3GGXmikH2MdTeGY1D711EORX/lVXpr+ecGgqfUWF8MPB07XkYuJ54DAuYT318+2XrzMjOtqkT94VkXmxv6dFGhG8YZ8vNMPd4tdj9c0lpvWQdqXtL1TlFRpD/P6UMEigfN0c9oWDg9U7Ilymgei0UXtf1gtcQbc5sSQU0S4vr9YJp2gLFIGK11Iqg4XSGdcI0QWLLkkC6cBukhVnd6BCYbLjTYy3fNs4DzNdemJlxGl8sLexFytBF6YApvSdus3nFXaMCtBGx16HzkK9ne3lobAwL2o79bP4imEGqg+ibvyNmbrwFGnQrBc1jTF9LyQX9q+louxVfHs6ZiVw==_

and my implementation is strict to base64url string, so I want to know is this by design ? Does the implementation of Base64Encoder.Decode should be compatible with base64 strings ? So I can move forward to do some extra work.
Thanks.

**Comment by brentschmaltz** [comment] 2021-09-28 16:27
@zsybupt If this is a valid base64url encoded string, the decode should succeed.
@cesarpayan please have a look at this.

**Comment by 8ggmaker** [comment] 2021-09-29 06:46
@brentschmaltz it is a base64 string, there are '+' and '=', but the current implementation is compatible with base64 string, so the test is successful in dev branch

**Comment by 8ggmaker** [comment] 2021-09-29 06:53
@cesarpayan Add more snapshot for your investigation here: (ignore the Decode line number, I have changed the implementation in my local branch, and the log shows the call stacks, there are several other test failures, and should be the same problem)
![image](https://user-images.githubusercontent.com/3711046/135217567-fa2220eb-f054-4fc6-a59b-0ece244d4d7a.png)

**Comment by bgavrilMS** [comment] 2021-09-29 15:28
base64 and base64url encodings are different things. See https://stackoverflow.com/questions/55389211/string-based-data-encoding-base64-vs-base64url

base64url encodes some chars differently and includes some padding

**Comment by 8ggmaker** [comment] 2021-09-29 16:19
@bgavrilMS yes, the only situation that a base64 string is also a valid base64url string is:
1. no '+' and '/'
2. no paddings ('=') need,

the unit test calls Base64UrlEncoder with a base64 string here (not a valid base64url string):

rCz8Sn3GGXmikH2MdTeGY1D711EORX/lVXpr+ecGgqfUWF8MPB07XkYuJ54DAuYT318+2XrzMjOtqkT94VkXmxv6dFGhG8YZ8vNMPd4tdj9c0lpvWQdqXtL1TlFRpD/P6UMEigfN0c9oWDg9U7Ilymgei0UXtf1gtcQbc5sSQU0S4vr9YJp2gLFIGK11Iqg4XSGdcI0QWLLkkC6cBukhVnd6BCYbLjTYy3fNs4DzNdemJlxGl8sLexFytBF6YApvSdus3nFXaMCtBGx16HzkK9ne3lobAwL2o79bP4imEGqg+ibvyNmbrwFGnQrBc1jTF9LyQX9q+louxVfHs6ZiVw==
let's consider the current implementation (use .NET45 as an example)
```c#
#if NET45
            // 62nd char of encoding
            str = str.Replace(base64UrlCharacter62, base64Character62); // no replace for a base64 string
            
            // 63rd char of encoding
            str = str.Replace(base64UrlCharacter63, base64Character63);// no replace for a base64 string

            // check for padding
            switch (str.Length % 4) // always 0, base64 string add paddings to be multiple of 4
            {
                case 0:
                    // No pad chars in this case
                    break;
                case 2:
                    // Two pad chars
                    str += doubleBase64PadCharacter;
                    break;
                case 3:
                    // One pad char
                    str += base64PadCharacter;
                    break;
                default:
                    throw LogHelper.LogExceptionMessage(new FormatException(LogHelper.FormatInvariant(LogMessages.IDX10400, str)));
            }

            return Convert.FromBase64String(str); // reach here and return the bytes
#else
```
so this implementation works for both base64 string and base64url string.

**Comment by bgavrilMS** [comment] 2021-09-29 16:27
I see what you're saying - the Decode operation is too lax. It should maybe throw an exception if there are base64url illegal chars like `+`, but it doesn't.

I am asking because 2 other libs (MSAL and Microsoft.Identity.Web) copied this version of the helpers. But it looks like the Decode method wasn't changed. You are trying to make sure you don't introduce a regression.

**Comment by 8ggmaker** [comment] 2021-09-29 16:48
Yes, my implementation is strict to base64url string, and the test fails, so I want to know whether there are real use cases of decoding base64 string with Base64UrlEncoder beside the unit test, if it is by design, I can add base64 support to my implementation.

By the way, I checked the implementation of WebEncoders of asp.net core https://github.com/dotnet/aspnetcore/blob/main/src/Shared/WebEncoders/WebEncoders.cs

it does not throw exception either, so maybe it is ok to allow base64 string here 😄

**Comment by bgavrilMS** [comment] 2021-09-29 17:06
From my perspective, since we're dealing with OIDC / OAuth2 and other standards / RFCs which are pretty clear about their base64url, I think it's ok to be strict.  

But @brentschmaltz  and team have more experience with exotic IDPs.

**Comment by 8ggmaker** [comment] 2021-09-30 02:05
In my opinion, I think the upper layer should not use Base64UrlEncoder.Decode to decode a base64 string, no matter how the underlying implementation is, you know that you are dealing with a base64 string, so you should choice Convert.FromBase64String instead.
KeyingMaterial in Microsoft.IdentityModel.TestUtils
```c#
public static RSAParameters RsaParameters1
        {
            get => new RSAParameters
            {
                Exponent = Base64UrlEncoder.DecodeBytes("AQAB"),
                Modulus = Base64UrlEncoder.DecodeBytes("rCz8Sn3GGXmikH2MdTeGY1D711EORX/lVXpr+ecGgqfUWF8MPB07XkYuJ54DAuYT318+2XrzMjOtqkT94VkXmxv6dFGhG8YZ8vNMPd4tdj9c0lpvWQdqXtL1TlFRpD/P6UMEigfN0c9oWDg9U7Ilymgei0UXtf1gtcQbc5sSQU0S4vr9YJp2gLFIGK11Iqg4XSGdcI0QWLLkkC6cBukhVnd6BCYbLjTYy3fNs4DzNdemJlxGl8sLexFytBF6YApvSdus3nFXaMCtBGx16HzkK9ne3lobAwL2o79bP4imEGqg+ibvyNmbrwFGnQrBc1jTF9LyQX9q+louxVfHs6ZiVw==")
            };
        }
```

**Comment by brentschmaltz** [comment] 2021-09-30 15:51
@zsybupt yes technically you are correct.
The code above works and was probably just a cut and paste.

**Comment by cesarpayan** [comment] 2021-09-30 19:25
@zsybupt Thanks for bringing this up. We have discussed the pros and cons of what this change would bring and decided that we agree with you that the upper layer should not use Base64UrlEncoder.Decode to decode a base64 string. In addition to that:
- It can potentially introduce regression.
- The issue at hand comes from an unexpected usage of the encoder, as we indicate in the method's XML Documentation File, it decodes a Base64UrlEncoded.

Thanks, I'll go ahead and close the issue. Please feel free to reopen or create a new issue if you either encounter any issue or have any other question.

**Closed as completed by cesarpayan** 2021-09-30 19:25 UTC
Labels: P1, Customer reported, Investigate, Question
