### ISSUE TITLE
Extra characters at the end of encrypted JWT tokens don't prevent them from being considered valid

### ISSUE THREAD

**Issue by kevinchalet** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1641] opened 2021-05-04 19:26 UTC
Hey,

Yesterday, the following report was posted on the OpenIddict repository: https://github.com/openiddict/openiddict-core/issues/1254.

I was able to reproduce it on my machine and confirmed this was caused by IdentityModel.
It looks like IdentityModel doesn't reject a JWE payload if it contains extra characters after the authentication tag.

Here's a repro:

```csharp
using System.Diagnostics;
using System.Security.Claims;
using System.Security.Cryptography;
using Microsoft.IdentityModel.JsonWebTokens;
using Microsoft.IdentityModel.Tokens;

namespace ConsoleApp13
{
    class Program
    {
        static void Main(string[] args)
        {
            var identity = new ClaimsIdentity(TokenValidationParameters.DefaultAuthenticationType);
            var signingKey = new RsaSecurityKey(RSA.Create(2048))
            {
                KeyId = "id1"
            };

            var encryptionKey = new RsaSecurityKey(RSA.Create(2048))
            {
                KeyId = "id2"
            };

            var handler = new JsonWebTokenHandler();
            var token = handler.CreateToken(new SecurityTokenDescriptor
            {
                Audience = "audience",
                Issuer = "issuer",
                EncryptingCredentials = new EncryptingCredentials(encryptionKey, SecurityAlgorithms.RsaOAEP, SecurityAlgorithms.Aes256CbcHmacSha512),
                SigningCredentials = new SigningCredentials(signingKey, SecurityAlgorithms.RsaSha256Signature),
                Subject = identity
            });

            var parameters = new TokenValidationParameters
            {
                ValidAudience = "audience",
                ValidIssuer = "issuer",
                TokenDecryptionKey = encryptionKey,
                IssuerSigningKey = signingKey
            };

            var result = handler.ValidateToken(token + "A", parameters);
            Debug.Assert(!result.IsValid, "The token shouldn't be considered valid.");
        }
    }
}
```

@brentschmaltz @jennyf19 could you please take a look?

**Comment by brentschmaltz** [comment] 2021-05-05 19:48
Kévin,

Nice to hear from you, ill have a look.
Sometimes there are insignificant bits. For example, for a JWS some of the last bits can be changed due to Base64Eencoding or Base64UrlEncoding.
What is significant is if ANY bit in the CypherText can be changed.

Brent.

From: Kévin Chalet ***@***.***>
Sent: Tuesday, May 4, 2021 12:27 PM
To: AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet ***@***.***>
Cc: BrentSchmaltz ***@***.***>; Mention ***@***.***>
Subject: [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet] Extra characters at the end of encrypted JWT tokens don't prevent them from being considered valid (#1641)


Hey,

Yesterday, the following report was posted on the OpenIddict repository: openiddict/openiddict-core#1254<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopeniddict%2Fopeniddict-core%2Fissues%2F1254&data=04%7C01%7C%7Ca73ddfbaa47e4925eb8308d90f329de9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637557532331923810%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5AXZvIKW7Gg9rnekAsvpf26c4fbqjjZnqp1fnwjjd70%3D&reserved=0>.

I was able to reproduce it on my machine and confirmed this was caused by IdentityModel.
It looks like IdentityModel doesn't reject a JWE payload if it contains extra characters after the authentication tag.

Here's a repro:

using System.Diagnostics;

using System.Security.Claims;

using System.Security.Cryptography;

using Microsoft.IdentityModel.JsonWebTokens;

using Microsoft.IdentityModel.Tokens;



namespace ConsoleApp13

{

    class Program

    {

        static void Main(string[] args)

        {

            var identity = new ClaimsIdentity(TokenValidationParameters.DefaultAuthenticationType);

            var signingKey = new RsaSecurityKey(RSA.Create(2048))

            {

                KeyId = "id1"

            };



            var encryptionKey = new RsaSecurityKey(RSA.Create(2048))

            {

                KeyId = "id2"

            };



            var handler = new JsonWebTokenHandler();

            var token = handler.CreateToken(new SecurityTokenDescriptor

            {

                Audience = "audience",

                Issuer = "issuer",

                EncryptingCredentials = new EncryptingCredentials(encryptionKey, SecurityAlgorithms.RsaOAEP, SecurityAlgorithms.Aes256CbcHmacSha512),

                SigningCredentials = new SigningCredentials(signingKey, SecurityAlgorithms.RsaSha256Signature),

                Subject = identity

            });



            var parameters = new TokenValidationParameters

            {

                ValidAudience = "audience",

                ValidIssuer = "issuer",

                TokenDecryptionKey = encryptionKey,

                IssuerSigningKey = signingKey

            };



            var result = handler.ValidateToken(token + "A", parameters);

            Debug.Assert(!result.IsValid, "The token shouldn't be considered valid.");

        }

    }

}

@brentschmaltz<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrentschmaltz&data=04%7C01%7C%7Ca73ddfbaa47e4925eb8308d90f329de9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637557532331923810%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FGSwSXE%2FM41IBReLrD%2Bt4eV7ABBU7PrBR4DYZl%2BcokI%3D&reserved=0> @jennyf19<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjennyf19&data=04%7C01%7C%7Ca73ddfbaa47e4925eb8308d90f329de9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637557532331933804%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=upQoD5Koi90tZDc9cMn0WoU1TdR7AUbRda50hHyKHqM%3D&reserved=0> could you please take a look?

-

**Comment by kevinchalet** [comment] 2021-05-06 16:29
@brentschmaltz awesome, thanks!

> Sometimes there are insignificant bits.

That was my feeling too, but in this particular case, the "extra last bits" are considered by IdentityModel as being part of the authentication tag (which is expected since it's technically part of it): 

![image](https://user-images.githubusercontent.com/6998306/117332227-dd3d2a00-ae97-11eb-8595-87921c3d3e90.png)

I suspect IdentityModel correctly base64decodes it but only uses a fixed-size array copy that ignores the extra bytes before calling the crypto primitives. Feeding the crypto primitives with the original tag or adding a check in IdentityModel to ensure the authentication tag length matches the expected length would certainly help fix that issue.

**Comment by kevinchalet** [comment] 2021-06-19 13:55
Someone else emailed me to tell me they were concerned about this behavior. Do you have any news?

**Comment by brentschmaltz** [comment] 2021-07-12 21:50
@kevinchalet nothing yet, should get some time soon.

**Comment by jmprieur** [comment] 2024-04-21 18:45
Duplicate of #2201

**Closed as completed** 2024-05-01 00:17 UTC
Labels: P1, Customer reported, Investigate, Bug, IdentityModel8x
