### ISSUE TITLE
[Bug] WSTrustSerializationHelper.cs missing ReplyToAddress

### ISSUE THREAD

**Issue by danli123456** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2069] opened 2023-05-02 18:54 UTC
**Which version of Microsoft.IdentityModel are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [ ] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)
Microsoft.IdentityServer.IdentityModel

**Is this a new or an existing app?**

**Repro**
In the securitytokenresponse, theres the following field
<wsp:AppliesTo+xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
During Deserialization and Serialization, this field would get lost because the Serialization helper does not have this field as a constant

But in the trust serializationHelper class it does not serialize this field, as a result, during after serialization the token generation would fail since it's missing the applies to field 
```csharp
// code for serialization

private RequestSecurityTokenResponse SerializeRequestSecurityTokenResponse(string securityTokenResponseStr)
        {
            string byteOrderMarkUtf8 = Encoding.UTF8.GetString(Encoding.UTF8.GetPreamble());
            if (securityTokenResponseStr.StartsWith(byteOrderMarkUtf8))
            {
                securityTokenResponseStr = securityTokenResponseStr.Remove(0, byteOrderMarkUtf8.Length);
            }

            using (MemoryStream memoryStream = new MemoryStream())
            using (XmlReader xmlReader = XmlReader.Create(new StringReader(securityTokenResponseStr)))
            {
                WSTrust13ResponseSerializer serializer = new WSTrust13ResponseSerializer();
                WSTrustSerializationContext context = new WSTrustSerializationContext();
                RequestSecurityTokenResponse rstr = serializer.ReadXml(xmlReader, context);
                return rstr;
            }
        }
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).
The wstrustserializationHelper should be able to serialize replyTo address.

**Actual behavior**
A clear and concise description of what happens, e.g. an exception is thrown, UI freezes.
Error thrown:
System.InvalidOperationException: ID5024: The ReplyTo Address for the Relying Party was either not set or not a valid absolute URI. Override the SecurityTokenService.GetScope() method to supply the appropriate Scope.ReplyToAddress.\r\n   at System.IdentityModel.Services.FederatedPassiveSecurityTokenServiceOperations.ProcessSignInRequest(SignInRequestMessage requestMessage__COMMA__ ClaimsPrincipal principal__COMMA__ SecurityTokenService sts__COMMA__ WSFederationSerializer federationSerializer)\r\n   at

**Possible solution**

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots or links to code.

**Comment by brentschmaltz** [comment] 2023-05-17 04:30
@danli123456  WSTrustSerializationHelper is not a class in the WsTrust package, so i am unclear what the issue is.

**Comment by brentschmaltz** [comment] 2023-05-19 04:34
@danli123456 i am closing this as this bug appears to be in a different assembly.

**Closed as completed by brentschmaltz** 2023-05-19 04:34 UTC
Labels: Customer reported, Bug
