### ISSUE TITLE
Token validation doesn't use the require audience parameter

### ISSUE THREAD

**Issue by DaveBrue** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1548] opened 2020-10-29 19:11 UTC
System.IdentityModel.Tokens.Jwt v6.8.0

```
var credentials = new SigningCredentials(new JsonWebKey("<insert RSA keypair>"), "RS256");

var handler = new JwtSecurityTokenHandler();
var jwt = handler.CreateEncodedJwt(new SecurityTokenDescriptor { SigningCredentials = credentials });
var token = handler.ReadJwtToken(jwt);
Assert.Empty(token.Audiences);

var parameters = new TokenValidationParameters { RequireAudience = false, IssuerSigningKey = credentials.Key };
handler.ValidateToken(jwt, parameters, out var _);
// SecurityTokenInvalidAudienceException
// IDX10208: Unable to validate audience. validationParameters.ValidAudience is null or whitespace and validationParameters.ValidAudiences is null.
```

The token doesn't have an audience and it throws an audience exception but the RequireAudience parameter is false so it shouldn't throw.

**Comment by brentschmaltz** [comment] 2020-10-29 20:03
Closed, seems to be a dupe of : https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1547

**Closed as completed by brentschmaltz** 2020-10-29 20:03 UTC
