### ISSUE TITLE
Expiration date is limited to  Tue, 19 Jan 2038 03:14:07 GMT

### ISSUE THREAD

**Issue by wvdd007** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#92] opened 2015-01-29 12:21 UTC
I was using the version 0.1.0 of the nuget up until now.  We are switching to the new nuget.  To make sure that everything which worked before still works, I wrote some regression tests.  One of them is "a token that was valid using the old handler should still be valid".  To be able to test this, a serialized tons of jwt tokens using all of my RP settings and created a fake token with an expiration date at new DateTime(4321, 1, 1).  (To be easy to visually see if it is correct)  To my surprise this test failed with the current implementation. "IDX10225: Lifetime validation failed. The token is missing an Expiration Time.".  I reverified my token which had ""nbf":0,"exp":74190380400".  After a debugging session I noticed that there was an overflow exception (which is eaten by the handler).  I saw that the claim is read using an int32.  In practical situations this might be enough but I would have preferred the usage of an int64 for this.  What do you think ?

**Comment by brentschmaltz** [comment] 2015-01-30 16:03
I used int32 as it maps nicely to epoch time. You are correct that in 2038, it wraps. 
I think it is worth consideration.

**Comment by wvdd007** [comment] 2015-01-31 22:06
In theory this is a detail.  In practice, we've had the fuzz about Y2K and we somehow would avoid something similar (although I fully admit that 2038 is still a lot of time).  It's up to you what you do with it.

**Comment by tushargupta51** [comment] 2015-07-29 20:20
Closing this issue for now, 2038 is way in the future. We can revisit this later.

**Comment by MarkDuckworth** [comment] 2019-01-31 19:14
This is still a bug, please reopen.

**Comment by silverferrum** [comment] 2019-10-24 09:23
This is still a bug, please reopen. (2)

**Comment by brentschmaltz** [comment] 2019-10-24 15:28
@silverferrum Changing JwtPayload.Exp to long? would be breaking and would cause problems for many users.

We could add a new property that returns long?
We are favoring JsonWebToken and when we add the Exp property, we will add it as a long?.

**Comment by silverferrum** [comment] 2019-10-29 12:40
@brentschmaltz hi!
Problem is that if we specify expiration after 2038-1-19 the token will be generated with correct exp value. But when we attempt to validate such token the error will be returned in header 
**www-authenticate: Bearer error="invalid_token", error_description="The token has no expiration"**

So I cannot advise you how to fix that because I do not use JwtPayload.Exp property directly but the AuthorizeAttribute does.

**Comment by brentschmaltz** [comment] 2019-10-30 14:51
@silverferrum I am curious why you need a date so far in the future?

Can you share how you are using the AuthorizeAttribute?

**Comment by brentschmaltz** [comment] 2019-10-30 23:00
@silverferrum the problem is the api returns an int (our mistake). If we change it to return a long we will break users. That is why we would need a new API. Breaking users is a really bad thing in today's world of multiple dependencies.

**Comment by silverferrum** [comment] 2019-10-31 17:57
I think you are right. Maybe, adding the long field with marking the int field as obsolete will be good idea for a couple of years.

**Comment by stukselbax** [comment] 2021-11-22 13:32
Today is 22.11.2021, problem still exist - System.IdentityModel.Tokens.Jwt, Version=6.14.1.0.

Please, introduce major release with Y2K fix.

One day the users with old version of this package will get broken application. That's sad.

**Comment by vcsjones** [comment] 2021-12-23 17:58
A developer reported an issue to dotnet/runtime that was ultimately this issue. https://github.com/dotnet/runtime/issues/63001#issuecomment-999593705

**Comment by ggeurts** [comment] 2022-03-07 10:44
This issue has cost me days of work trouble shooting. Please make the Int32 value obsolete and add an 64-bit version of the property that gets used by the validators.

**Comment by brentschmaltz** [comment] 2022-03-09 17:19
@ggeurts ouch, that is painful.
Yes we will add a new API.

**Comment by andylai** [comment] 2022-04-12 03:06
Is this issue has been solved? Or still the same? 
I have faced this issue recently.
Any solution? 
Thanks.

**Comment by brentschmaltz** [comment] 2022-04-13 15:38
@andylai we haven't got to it yet.

**Comment by Exadra37** [comment] 2022-04-15 18:49
On  same boat here, spent some days trying to figure out what was wrong until I landed here.

**Comment by jaslam94** [comment] 2022-05-04 14:25
The problem still exists.

**Comment by mus65** [comment] 2022-06-27 13:57
For anyone who needs a workaround: we worked around this by setting TokenValidationParameters.RequireExpirationTime to false if exp overflows.

```
if (
  DateTime.UtcNow.Year < 2038 &&
  jwtTokenParsed.Payload.TryGetValue("exp", out object expObj) &&
  expObj is long exp &&
  exp > int.MaxValue
)
{
  requireExpirationTime = false;
}
```

**Comment by nikolaytashev** [comment] 2023-02-06 12:48
I need this one fixed. The workarounds doesn't work for me.

**Comment by jhonathanc** [comment] 2023-03-13 13:10
> For anyone who needs a workaround: we worked around this by setting TokenValidationParameters.RequireExpirationTime to false if exp overflows.
> 
> ```
> if (
>   DateTime.UtcNow.Year < 2038 &&
>   jwtTokenParsed.Payload.TryGetValue("exp", out object expObj) &&
>   expObj is long exp &&
>   exp > int.MaxValue
> )
> {
>   requireExpirationTime = false;
> }
> ```

This workaround is very limited because the time validation may be different for different bearers (e.g., different users with different roles, different systems with different expiration times...) and some bearers need to be validated against time (with a short period of time, like 5 minutes) and others "don't" (15 years). I agree it may solve the issue for some users that has only one expiration time, but for others, it will just remove an important validation.

**Comment by mus65** [comment] 2023-03-13 21:24
> > For anyone who needs a workaround: we worked around this by setting TokenValidationParameters.RequireExpirationTime to false if exp overflows.
> > ```
> > if (
> >   DateTime.UtcNow.Year < 2038 &&
> >   jwtTokenParsed.Payload.TryGetValue("exp", out object expObj) &&
> >   expObj is long exp &&
> >   exp > int.MaxValue
> > )
> > {
> >   requireExpirationTime = false;
> > }
> > ```
> 
> This workaround is very limited because the time validation may be different for different bearers (e.g., different users with different roles, different systems with different expiration times...) and some bearers need to be validated against time (with a short period of time, like 5 minutes) and others "don't" (15 years). I agree it may solve the issue for some users that has only one expiration time, but for others, it will just remove an important validation.

This actually works in our case because we are creating a new TokenValidationParameters instance for every single validation (we are not using using the ASP.NET Core extension methods where this may not be possible).

But yes, it's a bad workaround and I'm quite dissappointed that this still hasn't been fixed. 2038 is not that far off anymore and the longer the fix takes, the more legacy software will be broken by this.

**Comment by cakescience** [comment] 2023-05-14 07:01
Any news about this issue please?

**Comment by michaelhachen** [comment] 2023-06-15 09:57
Same problem here. We really need a fix for this!

**Comment by jbcullis** [comment] 2023-06-23 02:38
Yeah, this needs to be fixed....reported 8 years ago and the problem persists?
Seems to be a .net issue more than a AD issue as we are running into this on a .net7 web app.

**Comment by jennyf19** [comment] 2023-09-11 00:52
This is fixed in IdentityModel 7.

**Closed by jennyf19** 2023-09-11 00:52 UTC
Labels: Enhancement, P2, Customer reported

**Comment by KalleOlaviNiemitalo** [comment] 2023-09-11 03:16
IIUC, IdentityModel 7 doesn't support .NET Framework (<https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2123>); how can I get the year 2038 fix for .NET Framework?
