### ISSUE TITLE
[Bug] Method not found Exception when reading JWT token (Base64UrlEncoder.UnsafeDecode)

### ISSUE THREAD

**Issue by JFFby** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2577] opened 2024-05-01 13:09 UTC
**Which version of Microsoft.IdentityModel are you using?**
7.5.1

**Where is the issue?**
 * M.IM.JsonWebTokens

**Is this a new or an existing app?**

**Repro**

I am just trying to add JWT authentication to the existed app

```csharp
services.AddAuthentication()
.AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
{
    options.Audience = apiName;
    options.Authority = identityServerUrl;
});
```

**Expected behavior**
Acess token successfully validated

**Actual behavior**
A clear and concise description of what happens, e.g. an exception is thrown, UI freezes.

**Possible solution**
I am getting exception:
```
IDX14100: JWT is not well formed, there are no dots (.).
The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.
```
Which has inner one with message:
```
Method not found: 'Byte[] Microsoft.IdentityModel.Tokens.Base64UrlEncoder.UnsafeDecode(System.ReadOnlyMemory`1<Char>)'.
```
With call stack:
```
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebToken.ReadToken(String encodedJson)
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebToken..ctor(String jwtEncodedString)
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ReadToken(String token, TokenValidationParameters validationParameters)
```
**Additional context / logs / screenshots / links to code**

I double checked all dependencies, and they look good for me.
```Project '***' has the following package references
   [net8.0]:
   Top-level Package                                      Requested   Resolved
   > Microsoft.AspNetCore.Authentication.JwtBearer        8.0.4       8.0.4
   > Microsoft.Extensions.DependencyInjection             8.0.0       8.0.0
   > Microsoft.IdentityModel.JsonWebTokens                7.5.1       7.5.1
   > Microsoft.IdentityModel.Protocols.OpenIdConnect      7.5.1       7.5.1
   > Microsoft.IdentityModel.Tokens                       7.5.1       7.5.1
   > OpenIddict.Abstractions                              5.5.0       5.5.0
   > StyleCop.Analyzers                                   1.1.118     1.1.118
   > System.IdentityModel.Tokens.Jwt                      7.5.1       7.5.1

   Transitive Package                                           Resolved
   > Microsoft.Extensions.DependencyInjection.Abstractions      8.0.1
   > Microsoft.Extensions.Primitives                            8.0.0
   > Microsoft.IdentityModel.Abstractions                       7.5.1
   > Microsoft.IdentityModel.Logging                            7.5.1
   > Microsoft.IdentityModel.Protocols                          7.5.1
```

**Comment by pmaytak** [comment] 2024-05-02 16:07
@JFFby Does that dependency list include transitive packages?

`dotnet list yourcsrpoj.csproj package --include-transitive`

Can you provide the full call stack?

This may be related to #2504 but that method was internal.

**Comment by JFFby** [comment] 2024-05-03 13:11
Hey @pmaytak,
Yes, this list includes transitive packages and this is the full call stack related to the given exception.

**Comment by keegan-caruso** [comment] 2024-05-06 17:57
hi @JFFby I am not able to reproduce this. Can you confirm that this doesn't repro on a clean new app?

**Comment by mesuttalebiacerpro** [comment] 2024-08-01 13:19
Same error. Is there any news on this thread?

**Comment by mesuttalebiacerpro** [comment] 2024-08-01 13:32
> Same error. Is there any news on this thread?

The error fixed by removing "Microsoft.IdentityModel.Tokens" packet.

**Comment by llgiant** [comment] 2024-08-12 06:00
> > Same error. Is there any news on this thread?
> 
> The error fixed by removing "Microsoft.IdentityModel.Tokens" packet.

Thank you, it also worked for me by removing "Microsoft.IdentityModel.Tokens" packet.

**Comment by keegan-caruso** [comment] 2024-08-13 01:16
Another issue with mismatched versions

**Closed as completed by keegan-caruso** 2024-08-13 01:16 UTC
Labels: P1, Bug, Regression

**Comment by quirinoflavio** [comment] 2024-08-28 23:15
> Another issue with mismatched versions

Fixed by updating IdentityModel packages in the HttpApi.Host project as described [here](https://github.com/abpframework/abp/issues/20145#issuecomment-2202052771).

**Comment by apkowalewski** [comment] 2024-09-09 14:33
> > > Same error. Is there any news on this thread?
> > 
> > 
> > The error fixed by removing "Microsoft.IdentityModel.Tokens" packet.
> 
> Thank you, it also worked for me by removing "Microsoft.IdentityModel.Tokens" packet.

Removing the packet also fixed it for me. Thanks!

**Comment by danielphelps** [comment] 2024-09-09 14:34
> > > > Same error. Is there any news on this thread?
> > > 
> > > 
> > > The error fixed by removing "Microsoft.IdentityModel.Tokens" packet.
> > 
> > 
> > Thank you, it also worked for me by removing "Microsoft.IdentityModel.Tokens" packet.
> 
> Removing the packet also fixed it for me. Thanks!

Literally just found this, also.  The packet apparently has some extension with a bug in it.

**Comment by Helius01** [comment] 2025-02-14 19:57
> Microsoft.IdentityModel.Tokens

Thanks dude i spent about 1 hour to fix it.

**Comment by nitinjaswal** [comment] 2025-02-23 13:05
Thanks man. It solved my issue too. I spent 2 hours to fix it

**Comment by f-rezanejad** [comment] 2025-03-01 10:55
it worked for me, thanks

**Comment by lanedirt** [comment] 2025-03-14 12:12
> > Same error. Is there any news on this thread?
> 
> The error fixed by removing "Microsoft.IdentityModel.Tokens" packet.

Removing the packages also worked for me to fix this error message. Thanks for the idea!

---

Some more information for anyone that runs into the `Missing method` error: 

After removing any explicitly added  `Microsoft.IdentityModel.*` NuGet packages from my WebAPI project, it worked again. I investigated the cause a little bit, and in my case these packages were already implicitly added by other NuGet packages. And upgrading the IdentityModel packages manually to a newer version apparently causes version conflicts with other included packages.

In my example, these were my implicit references to the `Microsoft.IdentityModel.Tokens` package:
<img width="396" alt="Image" src="https://github.com/user-attachments/assets/9d23b345-981d-4be8-bad2-e9fbf8c8c613" />

Removing the manually added packages and recompiling did the trick for me, and still keeps all references working.

**Comment by GuyHarel-Dev** [comment] 2025-04-11 19:02
Caused by this nuget, in my case:
```
    <PackageReference Include="Microsoft.IdentityModel.Tokens.Saml" Version="8.7.0" />
```
