### ISSUE TITLE
Can't update Azure Functions SDK because of JWT

### ISSUE THREAD

**Issue by petro2050** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1429] opened 2020-05-30 14:05 UTC
I'm currently on Microsoft.NET.Sdk.Functions 3.0.3 and trying to update to **3.0.7**. I'm using System.IdentityModel.Tokens.Jwt 6.6.0. When I update my function sdk, I get a runtime error.

`System.IO.FileNotFoundException: Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=6.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.File name: 'System.IdentityModel.Tokens.Jwt, Version=6.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'`

Please note that if I use Functions Sdk 3.0.7, I need to downgrade my JWT version to 5.5.0. So, the issue happens starting 5.6.0.

https://github.com/Azure/azure-functions-host/issues/6129

**Comment by mitchdenny** [comment] 2020-06-09 06:32
Just bumped into this as well.

**Comment by GeoK** [comment] 2020-06-12 19:35
@petro2050, @mitchdenny  - Can you try out the workaround specified in the Microsoft.NET.Sdk.Functions repo?

> For now, using <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput> is the right approach to getting around this. I'm going to close this issue and use Azure/azure-functions-host#5894 to track the fix.

https://github.com/Azure/azure-functions-vs-build-sdk/issues/397#issuecomment-615445340

**Comment by petro2050** [comment] 2020-06-20 02:01
@GeoK The workaround worked for me. Is it safe to keep this line in source control after the actual fix is rolled out? Also, can you explain what this line does?

**Comment by jmprieur** [comment] 2020-06-20 09:46
Also adding @bgavrilMS, as there was a similar issue in MSAL.NET

**Comment by GeoK** [comment] 2020-06-22 21:10
@petro2050 - Based on @brettsam's [comment](https://github.com/Azure/azure-functions-vs-build-sdk/issues/397#issuecomment-615445340) using __FunctionsSkipCleanOutput_ is the correct way to solve this issue.
The issue is tracked here: https://github.com/Azure/azure-functions-host/issues/5894

**Comment by brentschmaltz** [comment] 2020-06-23 18:12
Closing as the azure team made a fix.

**Closed as completed by brentschmaltz** 2020-06-23 18:12 UTC
Labels: Customer reported, Documentation, Bug
