### ISSUE TITLE
[Bug] ConfigurationManager should not cache "no configuration"

### ISSUE THREAD

**Issue by rmja** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1819] opened 2022-03-02 12:44 UTC
**Which version of Microsoft.IdentityModel are you using?**
dev

**Where is the issue?**
 * [ ] M.IM.JsonWebTokens
 * [ ] M.IM.KeyVaultExtensions
 * [ ] M.IM.Logging
 * [ ] M.IM.ManagedKeyVaultSecurityKey
 * [x] M.IM.Protocols
 * [ ] M.IM.Protocols.OpenIdConnect
 * [ ] M.IM.Protocols.SignedHttpRequest
 * [ ] M.IM.Protocols.WsFederation
 * [ ] M.IM.TestExtensions
 * [ ] M.IM.Tokens
 * [ ] M.IM.Tokens.Saml
 * [ ] M.IM.Validators
 * [ ] M.IM.Xml
 * [ ] S.IM.Tokens.Jwt
 * Other (please describe)

**Repro**
The current logic in `ConfigurationManager` is to cache "no configuration" in case the first call to the metadata endpoint fails.
This happens because the [timeout is extended here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b24470757799a9d1d75f5f16314857f6bdc444d8/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs#L148), even if there is no fallback configuration.

**Expected behavior**
`GetConfigurationAsync()` should retry to get get a configuration from the metadata endpoint if the first call fails and not fallback and use a cached, empty configuration.

**Actual behavior**
`GetConfigurationAsync()` [continues to throw](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b24470757799a9d1d75f5f16314857f6bdc444d8/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs#L160) until the timeout expires.

**Possible solution**
Move [this line](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/b24470757799a9d1d75f5f16314857f6bdc444d8/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs#L148) to the below `else` clause. This will ensure that the timeout is only extended if there is a previous configuration that can be used as fallback.

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots or links to code.

**Comment by brentschmaltz** [comment] 2022-03-07 18:01
@rmja we will take case of this.

**Comment by saintarian** [comment] 2022-06-22 15:06
Any updates on this @brentschmaltz? We are encountering the same issue.

**Comment by kllysng** [comment] 2024-04-16 18:57
Hi @rmja and @saintarian, are you still experiencing this on the latest (7.5.1)? If so, could you please update with repo steps/expected behavior/actual behavior/possible solution as the source code has changed since this was last reported. Thank you 🙏

**Comment by rmja** [comment] 2024-04-16 19:38
I made changes back then to avoid this issue, so I no longer have a setup where I can reproduce this. I guess my initial description is reasonably clear, so it should be easy to inspect in the current code base if the issue persists.

**Comment by kllysng** [comment] 2024-04-17 17:01
Thanks @rmja! It looks to have been resolved based on the code changes in the file, so I'm going to close this. Please reopen if it does repo in the future.

**Closed as completed by kllysng** 2024-04-17 17:01 UTC
Labels: Customer reported, Bug, P3, More info needed
