### ISSUE TITLE
"IDX10503: Signature validation failed" along with "Keyset does not exist" on Linux

### ISSUE THREAD

**Issue by tugberkugurlu** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#319] opened 2015-11-22 16:22 UTC
I am getting the following exception on Linux while using `Microsoft.AspNet.Authentication.JwtBearer` library with an ASP.NET 5 application. I am not sure what's causing this as I don't get this under Windows.

```
ModernShopping_auth_sampleapp | System.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'System.IdentityModel.Tokens.X509SecurityKey - (thumbprint) : 6B7ACC520305BFDB4F7252DAEB2177CC091FAAE1
ModernShopping_auth_sampleapp | '.
ModernShopping_auth_sampleapp | Exceptions caught:
ModernShopping_auth_sampleapp |  'System.Security.Cryptography.CryptographicException: Keyset does not exist
ModernShopping_auth_sampleapp |   at System.Security.Cryptography.RSACryptoServiceProvider.Common (System.Security.Cryptography.CspParameters p) [0x00000] in <filename unknown>:0 
ModernShopping_auth_sampleapp |   at System.Security.Cryptography.RSACryptoServiceProvider..ctor (Int32 dwKeySize, System.Security.Cryptography.CspParameters parameters) [0x00000] in <filename unknown>:0 
ModernShopping_auth_sampleapp |   at System.Security.Cryptography.RSACryptoServiceProvider..ctor (System.Security.Cryptography.CspParameters parameters) [0x00000] in <filename unknown>:0 
ModernShopping_auth_sampleapp |   at System.IdentityModel.Tokens.RSACryptoServiceProviderProxy..ctor (System.Security.Cryptography.RSACryptoServiceProvider rsa) [0x00000] in <filename unknown>:0 
ModernShopping_auth_sampleapp |   at System.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor (System.IdentityModel.Tokens.AsymmetricSecurityKey key, System.String algorithm, Boolean willCreateSignatures) [0x00000] in <filename unknown>:0 
ModernShopping_auth_sampleapp |   at System.IdentityModel.Tokens.SignatureProviderFactory.CreateProvider (System.IdentityModel.Tokens.SecurityKey key, System.String algorithm, Boolean willCreateSignatures) [0x00000] in <filename unknown>:0 
ModernShopping_auth_sampleapp |   at System.IdentityModel.Tokens.SignatureProviderFactory.CreateForVerifying (System.IdentityModel.Tokens.SecurityKey key, System.String algorithm) [0x00000] in <filename unknown>:0 
ModernShopping_auth_sampleapp |   at System.IdentityModel.Tokens.X509SecurityKey.GetSignatureProvider (System.String algorithm, Boolean verifyOnly) [0x00000] in <filename unknown>:0 
ModernShopping_auth_sampleapp |   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature (System.Byte[] encodedBytes, System.Byte[] signature, System.IdentityModel.Tokens.SecurityKey key, System.String algorithm) [0x00000] in <filename unknown>:0 
ModernShopping_auth_sampleapp |   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature (System.String token, System.IdentityModel.Tokens.TokenValidationParameters validationParameters) [0x00000] in <filename unknown>:0 
ModernShopping_auth_sampleapp | '.
ModernShopping_auth_sampleapp | token: '{"typ":"JWT","alg":"RS256","x5t":"a3rMUgMFv9tPclLa6yF3zAkfquE","kid":"a3rMUgMFv9tPclLa6yF3zAkfquE"}.{"client_id":"ModernShoppingAuthSampleClient","scope":"write","sub":"0a568dc98b3e47e5a80d8fa6d07d209a","amr":["external"],"auth_time":1448208303,"idp":"Google","iss":"http://auth:44300","aud":"http://auth:44300/resources","exp":1448211907,"nbf":1448208307}'
ModernShopping_auth_sampleapp |   at Microsoft.IdentityModel.Logging.LogHelper.Throw (System.String message, System.Type exceptionType, EventLevel logLevel, System.Exception innerException) [0x00000] in <filename unknown>:0 
ModernShopping_auth_sampleapp |   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature (System.String token, System.IdentityModel.Tokens.TokenValidationParameters validationParameters) [0x00000] in <filename unknown>:0 
ModernShopping_auth_sampleapp |   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken (System.String securityToken, System.IdentityModel.Tokens.TokenValidationParameters validationParameters, System.IdentityModel.Tokens.SecurityToken& validatedToken) [0x00000] in <filename unknown>:0 
ModernShopping_auth_sampleapp |   at Microsoft.AspNet.Authentication.JwtBearer.JwtBearerHandler+<HandleAuthenticateAsync>d__1.MoveNext () [0x00000] in <filename unknown>:0 
```

This is the entire application: https://github.com/tugberkugurlu/ModernShopping/tree/12c9fb527e4892abb326b4486e8a92a06ba61db2/Auth

And this is where I use `JwtBearerAuthentication`: https://github.com/tugberkugurlu/ModernShopping/blob/12c9fb527e4892abb326b4486e8a92a06ba61db2/Auth/src/ModernShopping.Auth.SampleApp/Startup.cs#L70-L84

**Comment by PinpointTownes** [comment] 2015-11-22 16:44
Duplicate of https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/179 :smile:

**Comment by brentschmaltz** [comment] 2015-11-23 18:17
Please reopen if not a dup of #179

**Closed by brentschmaltz** 2015-11-23 18:17 UTC

**Comment by tugberkugurlu** [comment] 2015-11-23 18:36
I am not sure. @pinpointtownes pointed yesterday somewhere else to me that it's a different issue. I don't know any knowladge in this area to understand why this happens and whether it's possible to solve it here but it's annoying :(

**Comment by PinpointTownes** [comment] 2015-11-23 18:42
@tugberkugurlu nah nah, these two issues are definitely linked (but https://github.com/dotnet/corefx/issues/424 is a totally different one :smile:)
