### ISSUE TITLE
[Bug] IDX20803 - Unable to obtain configuration from 'System.String'

### ISSUE THREAD

**Issue by apetrut** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2031] opened 2023-02-24 20:43 UTC
Hi,

I am using IdentityModel version 6.0.0 and System.IdentityModel.Tokens.Jwt version 6.15.0.

I am getting the error below on the dev environment:

![image](https://user-images.githubusercontent.com/13006228/221287144-642b73b9-c076-4573-8bd4-9cfde76d6892.png)

Is there a setting that I've missed to configure?

**Comment by brentschmaltz** [comment] 2023-02-25 00:47
@apetrut when you say IdentityModel version 6.0.0 and System.IdentityModel.Tokens.Jwt 6.10.0 does that mean you are mixing assemblies versions in IdentityModel?

**Comment by apetrut** [comment] 2023-02-25 08:31
@brentschmaltz I am running the skoruba version of Duende software that behind the scenes is using the IdentityModel dlls. It's not someting I can control unfortunately.

**Comment by brentschmaltz** [comment] 2023-03-20 20:47
@apetrut there could be a problem if the IdentityModel assembly versions are not the same.

**Comment by justinmchase** [comment] 2023-09-26 15:23
I have this issue also, where its failing with this error specifically:

> System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://login.microsoftonline.com/db05faca-c82a-4b9d-b9c5-0f64b6755421/v2.0/.well-known/openid-configuration'. Will retry at '09/26/2023 03:33:02 +00:00'.

When I just use a regular HttpClient to get that url it works fine in the same process but when the `Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync` function tries to get it, it fails with this error randomly.

My server is requesting from within a corporate firewall which requires certain certs to be used to access this endpoint. The certs are on the machine and, like I said, that basic HttpClient would not be able to fetch the document if they weren't. So the issue really seems like the `Microsoft.IdentityModel` library is not using the system certificates by default somehow.

I'm not sure how to configure it to just use a basic HttpClient either.

**Comment by brentschmaltz** [comment] 2023-09-26 23:08
@justinmchase it sounds as if you are using mutual auth.
For many cases, TLS negotiates a session key to protect the channel using just the server cert.

**Comment by justinmchase** [comment] 2023-09-27 14:50
After a _lot_ of debugging, including completely replacing this library with an alternate method of token validation, I have found that this issue is still happening for me. Therefore it can't possibly be related to this library.

In my case I am about 90% sure that the reason for this error is that the certificate used for ssh to pull the jwks keys is failing because of my corporate firewall and not having the correct certs installed on my machine. Its a little complicated due to going through multiple layers of docker but I can say confidently that the issue is mine and not realted to this repo at all.

**Comment by brentschmaltz** [comment] 2023-09-27 15:23
@justinmchase it appears the jwkuri specified requires authentication.

@Tratcher any idea on how to instruct HttpClient to use mutual auth?

**Comment by Tratcher** [comment] 2023-09-27 16:41
@brentschmaltz, @justinmchase says it's unrelated?

**Comment by apetrut** [comment] 2023-09-27 18:13
> After a _lot_ of debugging, including completely replacing this library with an alternate method of token validation, I have found that this issue is still happening for me. Therefore it can't possibly be related to this library.
> 
> In my case I am about 90% sure that the reason for this error is that the certificate used for ssh to pull the jwks keys is failing because of my corporate firewall and not having the correct certs installed on my machine. Its a little complicated due to going through multiple layers of docker but I can say confidently that the issue is mine and not realted to this repo at all.

I had this similar issue which sounded like a library related thing, but it turned out that it had to do with the infrastructure access because the STS service could not communicate with Admin service via K8S and Azure App Gateway. In my case the Identity services were running inside a Kubernetes cluster which was sitting behind Azure App Gateway.
 
The solution was to take out the Identity services and deploy them as separate App Services outside K8S cluster.

**Comment by brentschmaltz** [comment] 2023-09-27 21:35
@apetrut thanks!

**Comment by jmprieur** [comment] 2023-09-28 01:10
Thanks for the update
Closing as external

**Closed as completed by jmprieur** 2023-09-28 01:10 UTC
Labels: Customer reported
