### ISSUE TITLE
Replace netstandard1.3 by netstandard1.4

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#354] opened 2016-03-24 22:26 UTC
With the recent changes in the crypto stack, Wilson needs to be updated to target `netstandard1.4` instead of `netstandard1.3`.

https://github.com/dotnet/corefx/commit/6e3e29dbec3705094a539b6b2dc863c5a8ee270c
https://github.com/aspnet/Security/commit/7ec3da701cebcd36df07367e06b321fb743fbf94

@tushargupta51 @brentschmaltz any chance this work item could be prioritized?

**Comment by tushargupta51** [comment] 2016-03-25 04:04
@PinpointTownes I will take a look at this tomorrow.

**Comment by PinpointTownes** [comment] 2016-03-25 11:21
@tushargupta51 thanks! Pushing a new version should also help fix that: https://github.com/openiddict/openiddict-core/issues/76#issuecomment-201058572.

**Comment by PinpointTownes** [comment] 2016-03-25 22:42
@tushargupta51 did you have a chance to give it a look? I'm fine submitting a PR if it can help.

**Comment by brentschmaltz** [comment] 2016-03-25 23:01
@PinpointTownes should be in soon.

**Comment by PinpointTownes** [comment] 2016-03-25 23:02
Marvelous, thanks guys! :clap:

**Comment by brentschmaltz** [comment] 2016-03-26 02:22
Fixed with PR #355

**Closed by brentschmaltz** 2016-03-26 02:22 UTC
Labels: Fix 5.x, P1, User reported

**Comment by PinpointTownes** [comment] 2016-03-27 14:01
FYI, there's probably a bug in your build process, because the netstandard TFM added in the nuspec file is invalid:

```csharp
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>Microsoft.IdentityModel.Protocols.OpenIdConnect</id>
    <version>2.0.0-rc2-303270021</version>
    <authors>Microsoft.IdentityModel.Protocols.OpenIdConnect</authors>
    <owners>Microsoft.IdentityModel.Protocols.OpenIdConnect</owners>
    <licenseUrl>https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/LICENSE.txt</licenseUrl>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <description>Includes types that provide support for OpenIdConnect protocol.</description>
    <copyright>Copyright (c) Microsoft Corporation. All rights reserved.</copyright>
    <dependencies>
      <group targetFramework="Unsupported0.0">
        <dependency id="System.Dynamic.Runtime" version="4.0.11-rc2-23923" />
        <dependency id="Microsoft.IdentityModel.Protocols" version="2.0.0-rc2-303270021" />
      </group>
      <group targetFramework=".NETFramework4.5.1">
        <dependency id="Microsoft.IdentityModel.Protocols" version="2.0.0-rc2-303270021" />
      </group>
    </dependencies>
  </metadata>
</package>
```

**Comment by tushargupta51** [comment] 2016-03-28 02:31
@PinpointTownes It has been fixed, nuget.exe needs to be updated to one that understands the new TFM.

**Comment by PinpointTownes** [comment] 2016-03-28 07:10
The NuGet bug that was fixed recently mainly impacted the restore step and was poisoning the local packages store. Of course, I no longer have this buggy version locally and the weird bug I mentioned  directly impacts the nightly packages uploaded to MyGet (it's easy to confirm: download one of the nupkg files, open it as a ZIP archive and extract the nuspec file). Or maybe you mean you're using an old NuGet version to pack your packages?

**Comment by tushargupta51** [comment] 2016-03-28 07:15
@pinpointtownes I understand the bug in brent's pr was about using the right tfm. The issue that you reported was being caused by an old nuget version used by our build system that pushes packages to myget. I updated the version that our build system uses. You should the right nuspec in the latest myget package.

**Comment by PinpointTownes** [comment] 2016-03-28 07:17
Ah great, I'll give the new packages a try, thanks! :clap:

**Comment by PinpointTownes** [comment] 2016-03-28 07:19
Fix confirmed, the `2.0.0-rc2-303271754` packages are no longer impacted.

Thanks @tushargupta51 :tada:

**Comment by brentschmaltz** [comment] 2016-03-28 18:19
@tushargupta51 I thought the new nuget.exe was updated last week, at we hit the same thing.

**Comment by tushargupta51** [comment] 2016-03-28 18:47
@brentschmaltz Yes we did, but it was updated on Friday around 4 pm to older version.
