### ISSUE TITLE
JWT for Client Side Encryption and Server Side Decryption

### ISSUE THREAD

**Issue by jaffe9** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1250] opened 2019-09-08 07:17 UTC
Hi All,

I’m not sure if I’m trying something which is wrong or if its perfectly OK to try of something like this. I’m encrypting my client side using (https://github.com/kjur/jsrsasign) this library a PayLoad using public key of our own certificate. We are able to successfully generate a token. I’m trying to validate this generated token using the same certificate at the server side using (https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet) this library and we are always landing with a signature error like
IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey, KeyId: ‘6F566868C3825E94C6128131D991CD60503701B8’, InternalId: ‘59b1eb0e-9e00-4159-83c4-9b163f70c7f2’. , KeyId: 6F566868C3825E94C6128131D991CD60503701B8
'.
Exceptions caught:

‘’.*
token: ‘{“alg”:“RS256”}.{“Payload”:“Payload”}’.
I’m left with little or no clue and wasting my time playing with my certificate. By the way, I’m creating my certificate using the below commands:

openssl genrsa -des3 -out private.pem 2048
openssl rsa -in private.pem -outform PEM -pubout -out public. pem
openssl req -new -x509 -key private.pem -out publickey.cer -days 1825
openssl pkcs12 -export -out public_privatekey.pfx -inkey private.pem -in publickey.cer
Any help to help me proceed would be much appreciated guys. Thanks in Advance.

-Jaffar.

**Comment by GeoK** [comment] 2019-09-09 21:36
Hi @jaffe9 - could you provide a bit more info?
Are you using JsonWebTokenHandler (v5.5.0)?
Is _Exceptions caught:_ an empty string?

It would be very helpful if you could provide a small repro project.

**Comment by jaffe9** [comment] 2019-09-10 06:26
Hi @GeoK ,

Thanks for the response. I checked the Microsoft.IdentityModel.JsonWebTokens and found its version as 5.5.0.0. Since it is in PoC stage we created Adhoc methods, let me know if I'm doing anything wrong here. And yes, Exception Caught is always empty string.

If this isn't helping let me know so I can share the entire solution.

public bool IsTokenValid(string token)
        {
            if (string.IsNullOrWhiteSpace(token))
            { throw new ArgumentException("Input Token is Empty"); }

            TokenValidationParameters tokenValidationParams = GetTokenValidationParameters(token);
            JwtSecurityTokenHandler jwtSecurityTokenHandler = new JwtSecurityTokenHandler();
            //tokenValidationParams.ValidAudience = "http://www.anb.com.sa";
            //tokenValidationParams.ValidIssuer = "http://www.anb.com.sa";
            //tokenValidationParams.ValidIssuer = "ANB";
            IdentityModelEventSource.ShowPII = true;
            try
            {
                SecurityToken validatedToken;
                ClaimsPrincipal tokenValid = jwtSecurityTokenHandler.ValidateToken(token, tokenValidationParams, out validatedToken);
                return true;
            }
            catch (Exception e)
            {
                return false;
            }
        }

private TokenValidationParameters ValidateToken(string token)
        {
            var tokenHandler = new JwtSecurityTokenHandler();
            var certificate = new X509Certificate2(@"C:\Users\57880\Desktop\NewCertificate\public_privatekey.pfx", "anb123");
            var securityKey = new X509SecurityKey(certificate);

            var validationParameters = new TokenValidationParameters
            {
                //ValidAudience = "Others",
                //ValidIssuer = "Self",
                IssuerSigningKey = securityKey
            };

            return validationParameters;
            //SecurityToken securityToken;
            //var principal = tokenHandler.ValidateToken(token, validationParameters, out securityToken);
            //if (principal == null)
            //    return false;
            //if (securityToken == null)
            //    return false;

            //return true;
        }

**Comment by brentschmaltz** [comment] 2019-09-10 21:28
Can you show the entire roundtrip?
Creating and Validating?

Have you tried other Key types: Symmetric, RSA, ECD, just to rule out a cert issue?

**Comment by jaffe9** [comment] 2019-09-11 09:13
Hi @brentschmaltz,

Thanks for the reply. 
Creating using this library (https://github.com/kjur/jsrsasign), please navigate to jsrsasign-master/sample/sample_jwsgenerate2.html.
JWS Header: {"alg":"RS256"}
JWS Payload: {"PayLoad": "Jaffar"}
Signing PKCS#1 RSA Private Key: Private Key I had generated using OpenSSL

Validating the above session using the below code:

using System;
using System.Collections.Generic;
using System.Security.Claims;
using JWTSample.Model;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Cryptography;
using Microsoft.IdentityModel.Logging;
using System.Text;
using System.Security.Cryptography.X509Certificates;

namespace JWTSample.Manager
{
    public class JWTService : IAuthService
    {
        private RSA _rsa;
        public string SecretKey
        { get; set; }

        public JWTService(string secretKey)
        {
            SecretKey = secretKey;
        }

        public bool IsTokenValid(string token)
        {
            if (string.IsNullOrWhiteSpace(token))
            { throw new ArgumentException("Input Token is Empty"); }

            TokenValidationParameters tokenValidationParams = GetTokenValidationParameters(token);
            JwtSecurityTokenHandler jwtSecurityTokenHandler = new JwtSecurityTokenHandler();
            //tokenValidationParams.ValidAudience = "http://www.anb.com.sa";
            //tokenValidationParams.ValidIssuer = "http://www.anb.com.sa";
            //tokenValidationParams.ValidIssuer = "ANB";
            IdentityModelEventSource.ShowPII = true;
            try
            {
                SecurityToken validatedToken;
                ClaimsPrincipal tokenValid = jwtSecurityTokenHandler.ValidateToken(token, tokenValidationParams, out validatedToken);
                return true;
            }
            catch (Exception e)
            {
                return false;
            }
        }

        public IEnumerable<Claim> GetTokenClaims(string token)
        {
            if (string.IsNullOrEmpty(token))
                throw new ArgumentException("Given token is null or empty.");

            TokenValidationParameters tokenValidationParameters = GetTokenValidationParameters(token);
            tokenValidationParameters.ValidAudience = "http://www.anb.com.sa";
            tokenValidationParameters.ValidIssuer = "http://www.anb.com.sa";
            JwtSecurityTokenHandler jwtSecurityTokenHandler = new JwtSecurityTokenHandler();
            try
            {
                SecurityToken validatedToken;
                ClaimsPrincipal tokenValid = jwtSecurityTokenHandler.ValidateToken(token, tokenValidationParameters, out validatedToken);
                return tokenValid.Claims;
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        //private TokenValidationParameters GetTokenValidationParameters()
        //{
        //    return new TokenValidationParameters()
        //    {
        //        ValidateIssuer = true,
        //        ValidateAudience = true,
        //        ValidAudience = "http://www.anb.com.sa",
        //        RequireExpirationTime = true,
        //        IssuerSigningKey = GetSymmetricSecurityKey()
        //    };
        //}

        private TokenValidationParameters GetTokenValidationParameters(string tokenStr)
        {

            return ValidateToken(tokenStr);
        }

        //private SecurityKey GetSymmetricSecurityKey()
        //{
        //    //return null;
        //    //private readonly RSA rsa;
        //    byte[] symmetricKey = Convert.FromBase64String(SecretKey);
        //    //return new SymmetricSecurityKey(symmetricKey);
        //    //rsa = new RSACryptoServiceProvider(4096);
        //    //return new RsaSecurityKey(System.Security.Cryptography.RSA.Create(SecurityAlgorithms.RsaOAEP));
        //    //var IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(SecretKey));
        //    //return IssuerSigningKey;
        //    var keyBuilder = new SecurityTokenBuilder();
        //}


        /// <summary>
        /// 
        /// </summary>
        /// <param name="token"></param>
        /// <returns></returns>
        private TokenValidationParameters ValidateToken(string token)
        {
            var tokenHandler = new JwtSecurityTokenHandler();
            var certificate = new X509Certificate2(@"C:\Users\57880\Desktop\NewCertificate\public_privatekey.pfx", "anb123");
            var securityKey = new X509SecurityKey(certificate);

            var validationParameters = new TokenValidationParameters
            {
                //ValidAudience = "Others",
                //ValidIssuer = "Self",
                IssuerSigningKey = securityKey
            };

            return validationParameters;
            //SecurityToken securityToken;
            //var principal = tokenHandler.ValidateToken(token, validationParameters, out securityToken);
            //if (principal == null)
            //    return false;
            //if (securityToken == null)
            //    return false;

            //return true;
        }

        public string CreateToken(IANBModel Input)
        {
            DateTime issuedAt = DateTime.Now;
            DateTime expires = DateTime.Now.AddMinutes(1);

            var tokenHandler = new JwtSecurityTokenHandler();

            ClaimsIdentity claimsIdentity = new ClaimsIdentity(new[]
            {
                new Claim("Source Account", Input.SourceAccount),
                new Claim("Beneficiary Account",Input.BeneficiaryAccount),
                new Claim("Transfer Amount",Input.TransferAmount),
                new Claim("UDF1", Input.UDF[0])
            });

             byte[] symmetricKey = Convert.FromBase64String(SecretKey);
            var signingCredentials = new SigningCredentials(new SymmetricSecurityKey(symmetricKey), SecurityAlgorithms.HmacSha256Signature);
            //var securityKey = GetSymmetricSecurityKey();

            //var signingCredentials = new SigningCredentials(securityKey, SecurityAlgorithms.RsaOAEP);
            TokenManager();
            //var signingCredentials = new SigningCredentials(new RsaSecurityKey(_rsa), SecurityAlgorithms.Sha256Digest);
            IdentityModelEventSource.ShowPII = true;
            var token = (JwtSecurityToken)tokenHandler.CreateJwtSecurityToken(issuer: "http://www.anb.com.sa", audience: "http://www.anb.com.sa", subject: claimsIdentity, notBefore: issuedAt, expires: expires, signingCredentials: signingCredentials);
            //var token = (JwtSecurityToken)tokenHandler.CreateJwtSecurityToken(subject: claimsIdentity, notBefore: issuedAt, expires: expires, signingCredentials: signingCredentials);
            var tokenString = tokenHandler.WriteToken(token);
            return tokenString;
        }

        public RSA TokenManager()
        {
            // import instead of creating new, if necessary
            _rsa = new RSACryptoServiceProvider(2048);
            return _rsa;
        }
    }
}

**Comment by jaffe9** [comment] 2019-09-12 06:38
[JWTSample.zip](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/files/3604032/JWTSample.zip)
Just if in case you need the entire project. Just learned I can attach files to Github Comments. Regret the delay.

**Comment by GeoK** [comment] 2019-09-18 00:19
Hi @jaffe9, I was following your instructions and I was able to validate a token generated with jsrsasign lib, using IdentityModel.

1. Generated the private/public key pairs:
```
openssl genrsa -out private.pem 2048
openssl rsa -in private.pem -outform PEM -pubout -out public.pem
openssl req -new -x509 -key private.pem -out publickey.cer -days 1825
openssl pkcs12 -export -out public_privatekey.pfx -inkey private.pem -in publickey.cer
```

2. Used the key from _private.pem_ file to generate a token using [this tool](https://github.com/kjur/jsrsasign/blob/master/sample/sample_jwsgenerate2.html).

3. Used _publickey.cer_ to create an X509SecurityKey and use it for signature validation:
```
var cert = new X509Certificate2();
cert.Import(certFileLocation);
var securityKey = new X509SecurityKey(cert);

var tokenValidationParameters = new TokenValidationParameters()
{
    ValidateAudience = false,
    ValidateIssuer = false,
    ValidateIssuerSigningKey = false,
    ValidateLifetime = false,
    IssuerSigningKey = securityKey,
};

string jwtString = "eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ....";
var tokenHandler = new JsonWebTokenHandler();
var tokenValidationResult = tokenHandler.ValidateToken(jwtString, tokenValidationParameters);
```

Note: I turned off audience/issuer/lifetime validation just for testing purposes.

**Comment by jaffe9** [comment] 2019-09-19 06:14
Hi @GeoK,

Thanks for the comment and pain taken to retry my issue. Let me try this out today as instructed and will post you an update here. Hopefully it works :-)

Thanks once again.

**Comment by jaffe9** [comment] 2019-09-25 06:18
Hi @GeoK,

Thank you so much, its working, can you spot what went wrong with my approach was it the certificate generation? I dont remember trying certificate with PKCS12. Or am I wrong with the way I verified it?

**Comment by GeoK** [comment] 2019-09-25 16:10
@jaffe9 - Great! I was following your instructions for certificate generation, so I assume that the issue is somewhere in your code.

**Comment by brentschmaltz** [comment] 2019-10-10 22:39
@jaffe9 closing this out.
Please reopen if you have any issues.

**Closed** 2019-10-10 22:39 UTC
Labels: Investigate, User reported
