### ISSUE TITLE
System.IdentityModel.Tokens.Jwt Breaking Changes?

### ISSUE THREAD

**Issue by jlegan** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#109] opened 2015-03-27 17:57 UTC
I posted this on Thinktecture's site as I am working with IdentityServer but wanted to post in here in case this is a known, breaking change that has a quick fix. I reviewed the code and it looks like what I am seeing is not expected but I can confirm it in a new solution with NuGet fully updated.

Has anyone updated to v4.0.2.202250711 of System.IdentityModel.Tokens.Jwt yet?

All of the extension points I was using off of the OpenIdConnectAuthenticationNotifications (AcrValues, RequestType, IdTokenHint all broke when moving from 4.0.1 and I cannot find any documentation on the changes from Microsoft.

Example:
````
if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");
                            var postLogoutRedirectUri = CloudConfigurationManager.GetSetting("IdpRedirectUri");
                            if (idTokenHint != null)
                            {
                                n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                            }
                        }
```

**Comment by jlegan** [comment] 2015-03-27 18:06
This is an interesting one. It appears to be intellisense related. After I fixed a code defect I realized the projects were building even though VS is reporting that no symbols can be found. I reproduced it on a total of 3 workstations and neither cleaning the solution nor purging the intellisense settings allows the symbols to resolve properly after updating the nuget package.

**Comment by brentschmaltz** [comment] 2015-03-30 15:15
When you say broke, do you mean they don't get called?

**Comment by brentschmaltz** [comment] 2015-04-16 01:17
@jlegan is this still of interest to you?

**Comment by brentschmaltz** [comment] 2015-07-30 22:53
closing assuming the issue is resolved.

**Closed by brentschmaltz** 2015-07-30 22:53 UTC
Labels: User reported
