### ISSUE TITLE
[Bug] IDX10513 log message is dumping types instead of useful values

### ISSUE THREAD

**Issue by ohadschn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1961] opened 2022-11-09 18:45 UTC
**Which version of Microsoft.IdentityModel are you using?**
Latest from `dev` branch

**Where is the issue?**
 * [ ] M.IM.Logging

**Expected behavior**
IDX10513 contains useful information of the actual key and token.

**Actual behavior**
`IDX10513: Signature validation failed. Unable to match key: KeyInfo: 'Microsoft.IdentityModel.Xml.KeyInfo'. Exceptions caught: ''. 
 token: 'Microsoft.IdentityModel.Tokens.Saml2.Saml2SecurityToken`

**Possible solution**
Ideally override `ToString` on the classes (and their subclasses if applicable):
* `Microsoft.IdentityModel.Xml.KeyInfo` 
* `System.IdentityModel.Tokens.SecurityToken`

If that is somehow an issue, use some utility method to create a meaningful string when passed here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/59d1307a260829c0f8609a183a962aceaeffba89/src/Microsoft.IdentityModel.Tokens.Saml/Saml2/Saml2SecurityTokenHandler.cs#L470

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots or links to code.

**Comment by jmprieur** [comment] 2022-11-10 00:32
@ohadschn did you enable PII?
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII

**Comment by ohadschn** [comment] 2022-11-10 08:22
@jmprieur sorry I should have been explicit about it - yes, PII logging it is enabled. If it weren't, the `IDX` message above would have included the text `'[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'`

The problem is the classes themselves don't override `ToString()`. 
This can be easily verified, for example:

```cs
var ki = new Microsoft.IdentityModel.Xml.KeyInfo();
Console.WriteLine(ki.ToString()); // prints "Microsoft.IdentityModel.Xml.KeyInfo"
```

**Comment by ohadschn** [comment] 2022-11-10 12:28
@jmprieur could you please remove the `Question` & `answered` labels? (I don't have the permissions)

**Comment by jmprieur** [comment] 2022-11-10 23:57
@sruke for your information
cc: @TimHannMSFT for the prioritization.

**Comment by jmprieur** [comment] 2022-11-10 23:57
Thanks @ohadschn for your investigation!

**Comment by jennyf19** [comment] 2024-03-28 02:01
@ohadschn I believe this was fixed and is a duplicate of another issue. Going to close, but please re-open if that is not the case. Thank you.

**Closed as completed by jennyf19** 2024-03-28 02:01 UTC
Labels: Customer reported, Bug
