### ISSUE TITLE
IssuerSigningKeyResolver doesn't support async

### ISSUE THREAD

**Issue by punitsinghi** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1660] opened 2021-06-24 11:51 UTC
Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolver doesn't support async delegate and hence any async call is a blocking call.

        IssuerSigningKeyResolver = (token, securityToken, identifier, parameters) =>
                {
                    //async call here
                }

**Comment by mafurman** [comment] 2021-06-25 21:34
Thanks for bringing this to our attention!
At the current moment we don't provide any async delegates, but this is definitely a feature that we'll want to think about adding.

**Comment by Kyle0654** [comment] 2023-08-14 21:03
Is there any estimate on when this might be supported? Fetching a public key using a JKU during authentication isn't great when the code has to run synchronously.

**Comment by brentschmaltz** [comment] 2024-03-30 18:23
@jennyf19 we can combine all the delegates into one feature.

**Comment by adambajguz** [comment] 2024-06-10 09:46
The issue is quite long and important, are there any updates on in?

**Comment by keegan-caruso** [comment] 2024-08-07 17:55
Will be fixed in #2568

**Closed as completed by keegan-caruso** 2024-08-07 17:55 UTC
Labels: Enhancement, Customer reported
